### PR TITLE
Add CONTRIBUTORS file

### PR DESCRIPTION
**Pull request by Jinbobo**
See #44

### CODE REVIEW

**Comment by elifoster** [comment]
I don't really see the point since everyone is already listed in the extension.json.

**Comment by Jinbobo** [comment]
well this is my request. it is common practice to document people's contributions made prior to using vcs. that file you mentioned does not do that.

**Comment by elifoster** [comment]
How does it not do that?

**Comment by Jinbobo** [comment]
it does not state how i contributed to the extension.

**Comment by elifoster** [comment]
I guess

**Pull request merged**
